name: google_sign_in_dartio
description: Flutter package for Google Sign-In built in dart and support both Mobile and Desktop environments.
version: 0.3.0
homepage: https://github.com/lamnhan066/google_sign_in_dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.1
  google_sign_in_platform_interface: ^2.3.1
  shared_preferences: ^2.0.18
  shared_preferences_foundation: ^2.1.4
  shared_preferences_linux: ^2.1.4
  url_launcher: ^6.1.10
  url_launcher_macos: ^3.0.3
  crypto: ^3.0.2
  http: ^1.1.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.9.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/lib/main.dart
  - /example/web/index.html
